service: ${SERVICE}
runtime: python313
env: standard

instance_class: F1

entrypoint: uvicorn src.main:app --host 0.0.0.0 --port $PORT

env_variables:
  APP_ENV: ${APP_ENV}
  DATABASE_URL: ${DATABASE_URL}
  FIREBASE_API_KEY: ${FIREBASE_API_KEY}
  SECRET_KEY: ${SECRET_KEY}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  MAILJET_API_KEY: ${MAILJET_API_KEY}
  MAILJET_SECRET_KEY: ${MAILJET_SECRET_KEY}
  DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER: ${DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER}
  GCP_SERVICE_KEY_PATH: ${GCP_SERVICE_KEY_PATH}
  GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
  GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
  CORS_ORIGINS: ${CORS_ORIGINS}
  FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
  BACKEND_DOMAIN: ${BACKEND_DOMAIN}
  ADMIN_API_KEY: ${ADMIN_API_KEY}
  GCP_PROJECT_ID: ${GCP_PROJECT_ID}
  PUBSUB_RESYNC_TOPIC: ${PUBSUB_RESYNC_TOPIC}
  SINGLE_ORG_POLICY_ENABLED: False