service: spry-backend
runtime: python310
env: standard

instance_class: F1

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  APP_ENV: ${APP_ENV}
  SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
  FIREBASE_API_KEY: ${FIREBASE_API_KEY}
  SECRET_KEY:  ${SECRET_KEY}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY}
