services:
  db:
    image: postgres:latest
    container_name: spry_v2_db
    restart: always
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: spry_v2
      POSTGRES_USER: spry
      POSTGRES_PASSWORD: spry_pwd
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spry -d spry_v2"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spry_v2_web
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
      - ./demo_google_account_service_key:/app/demo_google_account_service_key
      - ./gcp-spry-backend-prod.json:/app/gcp-spry-backend-prod.json
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data_v2:
