# Makefile

# Variable for Alembic config file path
ALEMBIC_CONFIG = -c /code/migrations/alembic.ini

# Declare phony targets
.PHONY: help build run migrate upgrade revision

# Display help information
help:
	@echo "Makefile for FastAPI project with Alembic"
	@echo "Usage:"
	@echo "  make build      Build the Docker containers"
	@echo "  make run        Run the Docker containers"
	@echo "  make migrate    Run database migrations"
	@echo "  make upgrade    Apply database migrations"
	@echo "  make revision   Create a new database migration"

# Build Docker containers using docker-compose
build:
	docker-compose build

# Run Docker containers using docker-compose
run:
	docker-compose up

# Run database migrations to the latest version using Alembic
migrate:
	docker-compose run --rm  web alembic $(ALEMBIC_CONFIG) upgrade head

# Apply the latest database migrations
upgrade:
	docker-compose run --rm  web alembic $(ALEMBIC_CONFIG) upgrade head

# Create a new database migration with autogenerated changes
# Use 'msg' variable for the migration message
revision:
	@if [ -z "$(msg)" ]; then \
		echo "Error: Please provide a message for the new migration using 'msg' variable, e.g. make revision msg=\"add new table\""; \
		exit 1; \
	fi
	docker-compose run --rm  web alembic $(ALEMBIC_CONFIG) revision --autogenerate -m "$(msg)"
