"""SPRY add team to Organization

Revision ID: 033d4f3efc89
Revises: 4663e8c06c2d
Create Date: 2025-01-16 19:33:04.268222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033d4f3efc89'
down_revision: Union[str, None] = '4663e8c06c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['organization_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('organization_members', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('organization_members_added_by_id_fkey', 'organization_members', type_='foreignkey')
    op.drop_column('organization_members', 'added_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('added_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('organization_members_added_by_id_fkey', 'organization_members', 'users', ['added_by_id'], ['id'])
    op.alter_column('organization_members', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('organization_team_members')
    op.drop_table('organization_teams')
    # ### end Alembic commands ###
