"""SPRY-89 add Team

Revision ID: 128e6b02f55f
Revises: 383fded0f156
Create Date: 2024-07-23 12:01:04.743478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128e6b02f55f'
down_revision: Union[str, None] = '383fded0f156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.String(length=255), nullable=True),
    sa.Column('type_rate', sa.String(length=255), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('invited_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invited_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type_rate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('added_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name='invited_user_added_by_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='invited_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invited_user_pkey')
    )
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###
