"""SPRY add cost_type to Organization

Revision ID: 1a98454c31c7
Revises: e2f27a4da40e
Create Date: 2025-01-26 16:19:52.508836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a98454c31c7'
down_revision: Union[str, None] = 'e2f27a4da40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('cost_type', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('average_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'average_cost')
    op.drop_column('organizations', 'cost_type')
    # ### end Alembic commands ###
