"""SPRY add AgendaBeta

Revision ID: 2069803d7727
Revises: 82bdf684cd84
Create Date: 2025-06-02 10:19:52.895071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2069803d7727'
down_revision: Union[str, None] = '82bdf684cd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_beta',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('member_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda_beta')
    # ### end Alembic commands ###
