"""SPRY add hourly_cost to member

Revision ID: 26738673c3be
Revises: 2069803d7727
Create Date: 2025-07-17 14:59:04.564333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26738673c3be'
down_revision: Union[str, None] = '2069803d7727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('hourly_cost', sa.String(length=255), nullable=True))
    op.drop_column('organization_members', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('cost', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('organization_members', 'hourly_cost')
    # ### end Alembic commands ###
