"""SPRY replaced team with organization

Revision ID: 2a061281aaaf
Revises: 6628dfdb2a5f
Create Date: 2025-01-08 16:59:09.316815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a061281aaaf'
down_revision: Union[str, None] = '6628dfdb2a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.String(length=255), nullable=True),
    sa.Column('type_rate', sa.String(length=255), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teams_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('create_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['users.id'], name='teams_create_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('team_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type_rate', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('added_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name='team_members_added_by_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_members_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_members_pkey'),
    sa.UniqueConstraint('email', name='team_members_email_key')
    )
    op.drop_table('organization_members')
    op.drop_table('organizations')
    # ### end Alembic commands ###
