"""SPRY add calendar_email to OrganizationMemberCalendar

Revision ID: 3e384429ab9c
Revises: b5bbe7f05ce1
Create Date: 2025-08-06 21:03:14.830837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e384429ab9c'
down_revision: Union[str, None] = 'b5bbe7f05ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_member_calendars', sa.Column('calendar_email', sa.String(length=100), nullable=True))
    op.drop_column('organization_members', 'google_refresh_token')
    op.drop_column('organization_members', 'google_access_token')
    op.drop_column('organization_members', 'google_access_token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('google_access_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('organization_members', sa.Column('google_access_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organization_members', sa.Column('google_refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('organization_member_calendars', 'calendar_email')
    # ### end Alembic commands ###
