"""SPRY add status to OrganizationMember

Revision ID: 4663e8c06c2d
Revises: edd8502a44bd
Create Date: 2025-01-14 16:30:42.291919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4663e8c06c2d'
down_revision: Union[str, None] = 'edd8502a44bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_members', 'status')
    # ### end Alembic commands ###
