"""SPRY add safe removal for organization_members

Revision ID: 52bbd588f576
Revises: 40b56019e6e3
Create Date: 2025-09-29 09:22:23.322750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bbd588f576'
down_revision: Union[str, None] = '40b56019e6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agenda_beta_member_id_fkey', 'agenda_beta', type_='foreignkey')
    op.create_foreign_key('agenda_beta_member_id_fkey', 'agenda_beta', 'organization_members', ['member_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agenda_beta_member_id_fkey', 'agenda_beta', type_='foreignkey')
    op.create_foreign_key('agenda_beta_member_id_fkey', 'agenda_beta', 'organization_members', ['member_id'], ['id'])
    # ### end Alembic commands ###
