"""SPRY0-130 add Agenda

Revision ID: 6b8096ce84c1
Revises: 128e6b02f55f
Create Date: 2024-10-27 14:40:27.837325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8096ce84c1'
down_revision: Union[str, None] = '128e6b02f55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['create_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda_templates')
    # ### end Alembic commands ###
