"""add cost to Member

Revision ID: 7e24ac223cd0
Revises: 1a98454c31c7
Create Date: 2025-02-06 22:24:38.951768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e24ac223cd0'
down_revision: Union[str, None] = '1a98454c31c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('cost', sa.String(length=255), nullable=True))
    op.drop_column('organization_members', 'rate')
    op.drop_column('organization_members', 'type_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('type_rate', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organization_members', sa.Column('rate', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('organization_members', 'cost')
    # ### end Alembic commands ###
