"""SPRY add type to OrganizationTeam

Revision ID: 85409b08c251
Revises: 033d4f3efc89
Create Date: 2025-01-17 16:40:29.681519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85409b08c251'
down_revision: Union[str, None] = '033d4f3efc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_team_members', sa.Column('type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_team_members', 'type')
    # ### end Alembic commands ###
