"""SPRY-76 update User

Revision ID: a28b2dc4d5e8
Revises: 68ba4eb4cb2a
Create Date: 2024-06-25 11:24:54.584790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28b2dc4d5e8'
down_revision: Union[str, None] = '68ba4eb4cb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invite_token')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('invite_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
