"""SPRY add setting to Organization

Revision ID: e2f27a4da40e
Revises: 85409b08c251
Create Date: 2025-01-26 11:19:43.493238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f27a4da40e'
down_revision: Union[str, None] = '85409b08c251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('cost_is_active', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('organizations', sa.Column('cost_period', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('cost_visibility', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'cost_visibility')
    op.drop_column('organizations', 'cost_period')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'cost_is_active')
    # ### end Alembic commands ###
