"""SPRY add name to organization

Revision ID: fedb931cdf82
Revises: 26738673c3be
Create Date: 2025-07-20 19:22:02.609256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fedb931cdf82'
down_revision: Union[str, None] = '26738673c3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_admins')
    op.add_column('organizations', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'name')
    op.create_table('super_admins',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='super_admins_pkey'),
    sa.UniqueConstraint('email', name='super_admins_email_key')
    )
    # ### end Alembic commands ###
