"""2_add_calendar_tables

Revision ID: 0c5ded710902
Revises: 97c0fb06b3df
Create Date: 2026-01-11 14:24:10.463027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c5ded710902'
down_revision: Union[str, Sequence[str], None] = '97c0fb06b3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

calendar_type_enum = postgresql.ENUM(
    'GOOGLE', 'GOOGLE_SERVICE',
    name='calendartypeenum',
    create_type=False
)

calendar_event_status_enum = postgresql.ENUM(
    'CONFIRMED', 'TENTATIVE', 'CANCELLED',
    name='calendareventstatusenum',
    create_type=False
)

calendar_sync_status_enum = postgresql.ENUM(
    'SUCCESS', 'FAILED', 'IN_PROGRESS',
    name='calendarsyncstatusenum',
    create_type=False
)

attendee_response_enum = postgresql.ENUM(
    'NEEDS_ACTION', 'ACCEPTED', 'DECLINED', 'TENTATIVE',
    name='calendarattendeeresponsestatusenum',
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()


    for enum in (
        calendar_type_enum,
        calendar_event_status_enum,
        calendar_sync_status_enum,
        attendee_response_enum,
    ):
        enum.create(bind, checkfirst=True)
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_access_info_id', sa.UUID(), nullable=False),
    sa.Column('calendar_email', sa.String(length=128), nullable=False),
    sa.Column('type', calendar_type_enum, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_access_info_id'], ['users_access_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_access_info_id', 'calendar_email', name='uq_user_calendar_email')
    )
    op.create_table('calendar_cache_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_calendar_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=255), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_status', calendar_sync_status_enum, nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('sync_token', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('channel_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_calendar_id'], ['user_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_calendar_id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_timezone', sa.String(length=255), nullable=True),
    sa.Column('end_timezone', sa.String(length=255), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('status', calendar_event_status_enum, nullable=False),
    sa.Column('html_link', sa.Text(), nullable=True),
    sa.Column('hangout_link', sa.Text(), nullable=True),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('creator_email', sa.String(length=255), nullable=True),
    sa.Column('is_self_created', sa.Boolean(), nullable=False),
    sa.Column('recurring_event_id', sa.String(length=255), nullable=True),
    sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conference_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_calendar_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_calendar_id'], ['user_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_event_id', 'user_calendar_id', name='uq_event_calendar')
    )
    op.create_index('idx_calendar_events_date_range', 'calendar_events', ['user_calendar_id', 'start_datetime', 'end_datetime'], unique=False)
    op.create_index('idx_calendar_status', 'calendar_events', ['user_calendar_id', 'status'], unique=False)
    op.create_index('idx_events_synced_at', 'calendar_events', ['synced_at'], unique=False)
    op.create_index('ix_calendar_events_end_datetime', 'calendar_events', ['end_datetime'], unique=False)
    op.create_index('ix_calendar_events_google_event_id', 'calendar_events', ['google_event_id'], unique=False)
    op.create_index('ix_calendar_events_recurring_event_id', 'calendar_events', ['recurring_event_id'], unique=False)
    op.create_index('ix_calendar_events_start_datetime', 'calendar_events', ['start_datetime'], unique=False)
    op.create_table('organization_member_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_member_id', sa.UUID(), nullable=False),
    sa.Column('user_calendar_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_member_id'], ['organization_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_calendar_id'], ['user_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_member_id', 'user_calendar_id', name='uq_org_member_user_calendar')
    )
    op.create_table('calendar_event_attendees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('response_status', attendee_response_enum, nullable=False),
    sa.Column('organizer', sa.Boolean(), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('resource', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id', 'email', name='idx_event_attendee_unique')
    )
    op.create_index('ix_calendar_event_attendees_calendar_event_id', 'calendar_event_attendees', ['calendar_event_id'], unique=False)
    op.create_index('ix_calendar_event_attendees_email', 'calendar_event_attendees', ['email'], unique=False)
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_user_organization', 'organization_members', ['user_id', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    
    op.drop_constraint('uq_user_organization', 'organization_members', type_='unique')
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_calendar_event_attendees_email', table_name='calendar_event_attendees')
    op.drop_index('ix_calendar_event_attendees_calendar_event_id', table_name='calendar_event_attendees')
    op.drop_table('calendar_event_attendees')
    op.drop_table('organization_member_calendars')
    op.drop_index('ix_calendar_events_start_datetime', table_name='calendar_events')
    op.drop_index('ix_calendar_events_recurring_event_id', table_name='calendar_events')
    op.drop_index('ix_calendar_events_google_event_id', table_name='calendar_events')
    op.drop_index('ix_calendar_events_end_datetime', table_name='calendar_events')
    op.drop_index('idx_events_synced_at', table_name='calendar_events')
    op.drop_index('idx_calendar_status', table_name='calendar_events')
    op.drop_index('idx_calendar_events_date_range', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_table('calendar_cache_metadata')
    op.drop_table('user_calendars')
    
    for enum in (
        attendee_response_enum,
        calendar_sync_status_enum,
        calendar_event_status_enum,
    ):
        enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
