name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: >
            projects/786136769301/locations/global/workloadIdentityPools/dev-spryplan/providers/GitHub
          service_account: dev-spryplan@spry-398908.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify auth
        run: gcloud auth list
        
      - name: Set environment variables
        run: |
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> $GITHUB_ENV
          echo "SQLALCHEMY_DATABASE_URI=${{ secrets.SQLALCHEMY_DATABASE_URI }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "MAILJET_API_KEY=${{ secrets.MAILJET_API_KEY }}" >> $GITHUB_ENV
          echo "MAILJET_SECRET_KEY=${{ secrets.MAILJET_SECRET_KEY }}" >> $GITHUB_ENV
          echo "DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER=${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}" >> $GITHUB_ENV
          echo "GCP_SERVICE_KEY_PATH=${{ secrets.GCP_SERVICE_KEY_PATH }}" >> $GITHUB_ENV
          echo "GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Write service demo account files
        run: |
          mkdir -p "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}"
          echo '${{ secrets.GCP_SPRY_DEMO1_576_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo1_576.json"
          echo '${{ secrets.GCP_SPRY_DEMO2_619_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo2_619.json"
          echo '${{ secrets.GCP_SPRY_DEMO3_675_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo3_675.json"
          echo '${{ secrets.GCP_SPRY_DEMO4_832_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo4_832.json"
          echo '${{ secrets.GCP_SPRY_DEMO5_483_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo5_483.json"
          echo '${{ secrets.GCP_SPRY_DEMO6_150_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo6_150.json"
          echo '${{ secrets.GCP_SPRY_DEMO7_895_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo7_895.json"
          echo '${{ secrets.GCP_SPRY_DEMO8_455_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo8_455.json"
          echo '${{ secrets.GCP_SPRY_DEMO9_606_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo9_606.json"
          echo '${{ secrets.GCP_SPRY_DEMO10_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo10.json"

      - name: Write GCP account files
        run: |
          echo '${{ secrets.GCP_SERVICE_KEY_JSON }}' > "${{ secrets.GCP_SERVICE_KEY_PATH }}"

      - name: Prepare app.yaml
        run: |
          sed -i "s|\${APP_ENV}|${{ secrets.APP_ENV }}|g" app.yaml
          sed -i "s|\${SQLALCHEMY_DATABASE_URI}|${{ secrets.SQLALCHEMY_DATABASE_URI }}|g" app.yaml
          sed -i "s|\${SECRET_KEY}|${{ secrets.SECRET_KEY }}|g" app.yaml
          sed -i "s|\${GOOGLE_CLIENT_ID}|${{ secrets.GOOGLE_CLIENT_ID }}|g" app.yaml
          sed -i "s|\${GOOGLE_CLIENT_SECRET}|${{ secrets.GOOGLE_CLIENT_SECRET }}|g" app.yaml
          sed -i "s|\${MAILJET_API_KEY}|${{ secrets.MAILJET_API_KEY }}|g" app.yaml
          sed -i "s|\${MAILJET_SECRET_KEY}|${{ secrets.MAILJET_SECRET_KEY }}|g" app.yaml
          sed -i "s|\${DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER}|${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}|g" app.yaml
          sed -i "s|\${GCP_SERVICE_KEY_PATH}|${{ secrets.GCP_SERVICE_KEY_PATH }}|g" app.yaml
          sed -i "s|\${GCP_BUCKET_NAME}|${{ secrets.GCP_BUCKET_NAME }}|g" app.yaml

      - name: Deploy to App Engine (prod)
        run: |
          gcloud app deploy --quiet \
            --project "${{ secrets.GCP_PROJECT_ID }}" \
            --version "prod-${{ github.run_number }}" \
            --promote

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK (dev)
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set environment variables (dev)
        run: |
          echo "APP_ENV=${{ secrets.APP_ENV_DEV }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY_DEV }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID_DEV }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET_DEV }}" >> $GITHUB_ENV
          echo "MAILJET_API_KEY=${{ secrets.MAILJET_API_KEY_DEV }}" >> $GITHUB_ENV
          echo "MAILJET_SECRET_KEY=${{ secrets.MAILJET_SECRET_KEY_DEV }}" >> $GITHUB_ENV
          echo "DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER=${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}" >> $GITHUB_ENV
          echo "GCP_SERVICE_KEY_PATH=${{ secrets.GCP_SERVICE_KEY_PATH_DEV }}" >> $GITHUB_ENV
          echo "GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME_DEV }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "GOOGLE_REDIRECT_URI=${{ vars.GOOGLE_REDIRECT_URI }}" >> $GITHUB_ENV

      - name: Write service demo account files (dev)
        run: |
          mkdir -p "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}"
          echo '${{ secrets.GCP_SPRY_DEMO1_576_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo1_576.json"
          echo '${{ secrets.GCP_SPRY_DEMO2_619_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo2_619.json"
          echo '${{ secrets.GCP_SPRY_DEMO3_675_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo3_675.json"
          echo '${{ secrets.GCP_SPRY_DEMO4_832_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo4_832.json"
          echo '${{ secrets.GCP_SPRY_DEMO5_483_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo5_483.json"
          echo '${{ secrets.GCP_SPRY_DEMO6_150_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo6_150.json"
          echo '${{ secrets.GCP_SPRY_DEMO7_895_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo7_895.json"
          echo '${{ secrets.GCP_SPRY_DEMO8_455_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo8_455.json"
          echo '${{ secrets.GCP_SPRY_DEMO9_606_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo9_606.json"
          echo '${{ secrets.GCP_SPRY_DEMO10_JSON }}' > "${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}/spry_demo10.json"

      - name: Write GCP account files (dev)
        run: |
          echo '${{ secrets.GCP_SERVICE_KEY_JSON_DEV }}' > "${{ secrets.GCP_SERVICE_KEY_PATH_DEV }}"

      - name: Prepare app.yaml (dev)
        run: |
          sed -i "s|\${SERVICE}|${{ secrets.SERVICE_DEV }}|g" app.yaml
          sed -i "s|\${APP_ENV}|${{ secrets.APP_ENV_DEV }}|g" app.yaml
          sed -i "s|\${DATABASE_URL}|${{ secrets.DATABASE_URL }}|g" app.yaml
          sed -i "s|\${SECRET_KEY}|${{ secrets.SECRET_KEY_DEV }}|g" app.yaml
          sed -i "s|\${GOOGLE_CLIENT_ID}|${{ secrets.GOOGLE_CLIENT_ID }}|g" app.yaml
          sed -i "s|\${GOOGLE_CLIENT_SECRET}|${{ secrets.GOOGLE_CLIENT_SECRET }}|g" app.yaml
          sed -i "s|\${MAILJET_API_KEY}|${{ secrets.MAILJET_API_KEY }}|g" app.yaml
          sed -i "s|\${MAILJET_SECRET_KEY}|${{ secrets.MAILJET_SECRET_KEY }}|g" app.yaml
          sed -i "s|\${DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER}|${{ secrets.DEMO_GOOGLE_ACCOUNT_SERVICE_FOLDER }}|g" app.yaml
          sed -i "s|\${GCP_SERVICE_KEY_PATH}|${{ secrets.GCP_SERVICE_KEY_PATH_DEV }}|g" app.yaml
          sed -i "s|\${GCP_BUCKET_NAME}|${{ secrets.GCP_BUCKET_NAME_DEV }}|g" app.yaml
          sed -i "s|\${GOOGLE_REDIRECT_URI}|${{ vars.GOOGLE_REDIRECT_URI }}|g" app.yaml
          sed -i "s|\${CORS_ORIGINS}|${{ vars.CORS_ORIGINS }}|g" app.yaml
          sed -i "s|\${FRONTEND_DOMAIN}|${{ vars.FRONTEND_DOMAIN }}|g" app.yaml

      - name: Deploy to App Engine (dev)
        run: |
          gcloud app deploy --quiet \
            --project "${{ secrets.GCP_PROJECT_ID }}" \
            --version "dev-${{ github.run_number }}"
